- name: config catalogue service
  hosts: Catalogue
  become: yes
  tasks:
   - name: enable nodejs service
     command: dnf module enable nodejs:20 -y
   - name: install nodejs 20
     package: 
      name: nodejs
      state: present
   - name: create roboshop system user
     user: 
      name: roboshop
      system: true
      shell: /sbin/nologin
      /home: /app
      comment: "Roboshop System user"
   - name: create /app folder
     file:
      name: /app
      state: present
   - name: download catalogue files
     get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
       dest: /tmp/catalogue.zip
   - name: unzip catalogue
     unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
   - name: install artifacts dependecy
     community.general.npm:
      path: /app 
   - name: copy catalogue service
     copy:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
   - name: copy mongodb repo
     copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
   - name: Install mongodb client
     package:
      name: mongodb-mongosh
      state: present
   - name: check catalogue schema exist ot not
     shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
     register: catalogue_output
     tags:
      - mongodb
   - name: print catalogue_output
     debug:
      msg: "{{ catalogue_output }}"
      tags:
       - mongodb
   - name: load products
     shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
     when: catalogue_output.stdout | int < 0
     tags:
      - mongodb
   - name: deamon reload
     systemd_service:
      name: catalogue
      daemon_reload: true
   - name: enable and start catalogue
     service:
      name: catalogue
      state: restarted
      enabled: yes
  
        
     



