[local]
localhost

[Mongodb]
mongodb.devopsaium.online

[Redis]
redis.devopsaium.online

[Mysql]
mysql.devopsaium.online

[RabbitMQ]
rabbitmq.devopsaium.online

[Catalogue]
catalogue.devopsaium.online

[User]
user.devopsaium.online

[Cart]
cart.devopsaium.online

[Shipping]
shipping.devopsaium.online

[Payment]
payment.devopsaium.online

[UI]
devopsaium.online