- name: Config mysql
  hosts: Mysql
  become: yes
  tasks:
    - name: Install mysql 
      package: 
       name: mysql
       state: present
    - name: Start mysql
      service:
        name: mysql
        state: started
        enabled: yes
    - name: setup root password
      command: mysql_secure_installation --set-root-pass RoboShop@1