- name: roboshop All nodes
  hosts: local
  connection: local
  vars:
   instance: ["Mongodb", "Redis", "MySql", "RabbitMQ", "Catalogue", "User", "Cart", "Shipping", "Payments", "UI"]
   image_id: ami-0220d79f3f480ecf5
  tasks:
   - name: Stopping ec2 nodes
     amazon.aws.ec2_instance:
      state: stopped
      instance_name: "Roboshop-{{ item }}"
     loop: "{{ instance }}"