- name: roboshop All nodes
  hosts: local
  connection: local
  vars:
   instance: ["Mongodb", "Redis", "MySql", "RabbitMQ", "Catalogue", "User", "Cart", "Shipping", "Payments", "Frontend"]
   image_id: ami-0220d79f3f480ecf5
  tasks:
  #  - name: Create Roboshop nodes
     amazon.aws.ec2_instance: 
      name: "Roboshop-{{ item }}"
      instance_type: t3.micro
      image_id: "{{ image_id }}"
      security_groups:
       - "Roboshop-UI"
       - "Roboshop-{{ item }}"
     loop: "{{ instance }}"
     register: ec2_output
     ignor_error: true

   - name: printing output
     debug:
      msg: "{{ec2_output}}"
  - name: Delete roboshop nodes
     amazon.aws.ec2_instance: 
      state: absent
      name: "Roboshop-{{ item }}"
      wait: false
     loop:  "{{ instance }}"
     register: ec2_output
       
     

    